<?php
/*
  civiwwa_migrate - Migrations for CivIWWA.
  Copyright (C) 2016  Johan Vervloet

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function civiwwa_migrate_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => [
      'People' => ['class_name' => 'peopleMigration'],
      'Clubs' => ['class_name' => 'clubsMigration'],
      'Memberships' => [
        'class_name' => 'membershipsMigration',
        'dependencies' => ['People', 'Clubs'],
      ],
      'Edegem2013' => [
        'class_name' => 'edegem2013Migration',
        'dependencies' => ['People'],
      ],
    ],
  );
  return $api;
}